image:
  file: /.gitpod/Dockerfile

tasks:
  - name: Build Gazelle
    init: bazelisk build //:gazelle && exit
    openMode: tab-after
  - name: Install Trunk Linters
    init: trunk install && exit
    openMode: tab-after
