# Documentation available at: https://www.gitpod.io/docs/configure/workspaces

image:
  file: /.gitpod/Dockerfile

tasks:
  - name: Build Gazelle
    command: |
      bazelisk build //:gazelle
      exit
    openMode: tab-after
  - name: Install Trunk Linters
    init: |
      trunk install
      exit
    openMode: tab-after
